title: Sam Soffes
email: sam@soff.es
author: Sam Soffes
description: >-
  This is my blog. I also have a <a href="https://soff.es/" rel="external">website thing</a>.
baseurl: ""
url: "https://soffes.blog"
twitter_username: soffes
github_username:  soffes
timezone: America/Los_Angeles
encoding: utf-8
strict_front_matter: true
permalink: /:title
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
